name: Deploy PHP Static Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PHP
        run: sudo apt-get install -y php-cli

      - name: Serve PHP Locally & Convert to Static HTML
        run: |
          php -S localhost:8000 -t . &
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent http://localhost:8000/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./localhost_8000